# Generated by Django 3.2.7 on 2021-09-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField()),
                ('callnumber', models.TextField()),
                ('keyword', models.TextField()),
                ('max_price', models.BigIntegerField()),
            ],
        ),
    ]
